@startuml classes

class Note{
    Long id
    String title
    String body
}
class Item {
    Long id
    String title
    String description
    Boolean status
}
class Task{
    Integer priority
    Set<DayOfWeek> daysOfWeek
    Integer repititions
    Duration estimatedDuration
    List<String> subTasks
}
class Event{
    DateTime start
    DateTime end
}
class User{
    Long id
    String username
    String password
}

Task -> Item
Event -> Item

User "0..n" - "1" Note : Write
User "0..n" - "1" Item : Register

@enduml